# Generated by Django 5.0.4 on 2024-05-02 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User



def set_default_user(apps, schema_editor):
    YourModel = apps.get_model('home', 'YourModel')
    default_user = User.objects.first()  # Replace this with your desired default user
    YourModel.objects.filter(user=None).update(user=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_posts_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
