# Generated by Django 5.0.4 on 2024-05-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_posts_user'),
        ('home', '0006_alter_posts_user'),
    ]

    operations = [
    ]
